# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g autorest'

- task: CmdLine@2
  inputs:
    script: 'autorest --input-file=swagger.json --csharp --output-folder=csharp/Generated --namespace=Streetcred.ServiceClients --add-credentials --override-client-name=AgencyServiceClient'

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'csharp/**/*.csproj'
    versioningScheme: 'off'
    buildProperties: '-p:PackageVersion=$(packageVersion)'

